FROM node:10.16.0-alpine
RUN apk update && apk add --virtual build-dependencies build-base gcc wget git

WORKDIR /usr/src/app

COPY ./package.json .
RUN npm install
RUN npm install -g @angular/cli

ENTRYPOINT npm install && npm run dev
